### ISSUE TITLE
Determine stack

### ISSUE THREAD

**Issue by Apexal** [Apexal/wrathspriter#1]
What technologies should we use to create Wrathskeller?

Possible options:
- Flutter (mobile app)
- React Native (mobile app)
- React SPA (web app)
- Desktop app???

**Comment by BianoBonzo** [comment]
Through a website/desktop app, the most efficient and comfortable way for users to use the character tool would be if they are provided a QR code for them to take pictures/record videos for their character creation tool

**Comment by alexisvh** [comment]
Should be able to use character tool on mobile device, more intuitive especially for taking pictures for the character

**Comment by talios0** [comment]
I think we should prioritize a website that works on mobile and desktop rather than an app. We already have the user downloading the main application, Wrathskeller, so having them download more would be an inconvenience. I like the idea of using Flutter.

**Comment by Tevetron** [comment]
I think that an app, while nice, adds more additional work that isn't super necessary for us having a finished game.

**Comment by ThisMatt** [comment]
having a website allows for a variety of computers to be used, not just phones or just desktops

**Comment by V-aleria** [comment]
The best idea seems to be to write a website rather than an app since it's easier for people to access and create (and save) their characters. It's also easier to take pictures on their phones :)

**Comment by Apexal** [comment]
Well folks, it looks like we're going for a web app using React! Great comments.
