### ISSUE TITLE
How to send characters from the webapp to the game

### ISSUE THREAD

**Issue by talios0** [Apexal/wrathspriter#10]
Sending the characters will be a large problem to solve. There is the potential solution of making transfers local network only, linking to something external, creating some sort of direct connection to the webapp, downloading the files manually, and probably a bunch of others.

This feature is important because it is the basis for the game. Without it, we cannot use created characters in the game without resorting to some shenanigans (downloading manually ->emailing to self -> downloading on computer -> uploading to game)

Any ideas for how this could be done?

**Comment by Apexal** [comment]
We could have a public server that holds characters that the character tool sends to and the game reads from. The character tool generates a random code for the character, and then in the game you simply enter in the corresponding code to grab the character from the server.

Pros:
- very simple from a user perspective

Cons:
- we have to add a whole extra server and functionality for this!
- we'd have to make it hard/impossible to guess character codes for privacy reasons

**Comment by talios0** [comment]
> 

I like the idea, but this would run into the issue of being unable to send characters if you're connected to the internet, but can't connect to the server (for whatever reason). Maybe there should be a fallback way to send characters if a connection to the server is unavailable?

**Comment by Apexal** [comment]
Another idea... Make Wrathskeller a **web** game in the browser and use WebRTC to communicate! This could result in less performance, but realistically our game is not computationally expensive.

**Comment by Apexal** [comment]
Returning to the server idea, we might **need** a server to do the image editing like background removal, resizing, and checking if images match poses. At that point, we can just store characters on the server. Of course, we'd have to keep them private somehow while also making it seamless for users.

I propose each character gets a short alpha ID assigned to it like "AJGX" which can be entered into Wrathskeller and then fetched from the server. However, to prevent people guessing other codes and stealing characters, we can implement a timer for when a character is able to be fetched. When a user chooses "Use" on Wrathspriter for a character, it tells the server to mark the character as grabable for like 5 minutes or some short amount. Therefore, the window for stealing a character is remarkably small but users don't have to make accounts or anything.

Thoughts?

**Comment by Apexal** [comment]
I should also add that we've got a new contributor who's a Open Source Software student (and very good friend of mine!) who is interested in working on the server.

**Comment by Apexal** [comment]
Let's move forward with using Wrathserver for both pose recognition and character storing.
