### ISSUE TITLE
Help button function

### ISSUE THREAD

**Issue by talios0** [Apexal/wrathspriter#11]
## General Description
If we want to continue with the help button on each page, we need to implement the functionality of the help button. This initial implementation would not include precise details for each page, but just an example of the button pulling up a menu that could be used for help. Specific implementation per-page would be done later.

## Use
The help button should be displayed at the top-right corner of each page. Since we only have one page as of time of writing, it would only be on that page.

When the help button is pressed/clicked, a modal menu (menu over top the rest of the DOM) would be displayed with help.

The "help" is text that explains the page.

There should additionally be two ways to exit the menu. First through an exit button on the modal and secondly by pressing outside of the modal.

## References

![](https://i.stack.imgur.com/ACnj6.jpg)
![](https://ps.w.org/popup-maker/assets/screenshot-6.png?rev=2390476)
![](https://media.nngroup.com/media/editor/2019/06/05/attfeedbackprompt.jpg)

**Comment by Apexal** [comment]
I believe this is done, unless anything else is planned for the Help Button?

**Comment by talios0** [comment]
You're right. I forgot to link this to the pull request.
