### ISSUE TITLE
Camera Integration

### ISSUE THREAD

**Issue by ThisMatt** [Apexal/wrathspriter#23]
Being able to take pictures as well as uploading and editing them will be important.  Does React naturally have camera/picture access, or is there a dependency to integrate? Either way, I'd like to experiment with getting some functionality set up.

**Comment by Apexal** [comment]
Great point! React just handles UI stuff, so any camera stuff is just through normal JavaScript through browser APIs. Check out this guide for a full walk-through https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos 

We have to handle how to wrap that code up in React! We might want to make our lives easier and just use a library like this: https://www.npmjs.com/package/react-webcam

Feel free to start experimenting with this and let me know what questions you've got.
