### ISSUE TITLE
Generate TypeScript Progressive Web App template

### ISSUE THREAD

**Issue by Apexal** [Apexal/wrathspriter#3]
Progressive Web Apps work offline, load faster, and have access to things like native mobile apps do. It's perfect for our character creator idea!

The popular Create React App tool has great support for PWAs. And, it has great support for TypeScript which we'll be using (we haven't discussed it yet but I'll explain Friday).

We can generate the start of the codebase with this command from [here](https://web.dev/progressive-web-apps/):
```bash
npx create-react-app . --template cra-template-pwa-typescript
```

**Comment by talios0** [comment]
I think you might've meant to link to [this](https://create-react-app.dev/docs/making-a-progressive-web-app/) page from create-react-app.dev instead.
