### ISSUE TITLE
So how are we going to build these guys?

### ISSUE THREAD

**Issue by ThisMatt** [Apexal/wrathspriter#7]
I was thinking about how to structure the design of a character's sprites, particularly relating to how we want to handle Majors and Minors when designing moves, and have a couple ideas we should discuss.

The first thought is that all Major-Minor combinations have a unique set of moves. This would allow for adding specific personalities to each combo, but comes with a ton more design than other ideas. 

![Option 1](https://user-images.githubusercontent.com/98851950/152895113-3f8bf97f-c03b-42ae-be2e-1e5ec7ee8fc7.png)

To lighten our work load, I figure we could select a handful of moves to be considered "universal". Things like blocks, idles, jumps, and the like will be the same for any character, and a user won't have to take new pictures for these when switching archetypes. To make up for the sameness, we could always add multiple options for each animation ("stoic" or "energetic" idles) with funnier names if we want.

![Option 2](https://user-images.githubusercontent.com/98851950/152895224-fae60716-26e8-4fc4-a4a4-9f38c26fdede.png)

Still, having unique combinations may prove to be too much of a design load, And I've thought up two approaches:

1. Major and Minor are separate.
       A user would take a set of images to a set of templates for a Major and a Minor. CS Major and CS Minor would be completely different templates with no interaction. We could implement this a few ways. Minors could impact light moves, and Majors heavy/specials. However it's implemented, a user would take pictures for a Major, pictures for a Minor, and we'd slap 'em together for the finished character. Changing Majors wouldn't affect the Minor and vice versa, allowing for less time spent building and more time playing. This also allows for pure students to just pick their own discipline for both.

![Option 4](https://user-images.githubusercontent.com/98851950/152896030-158a3521-0706-4415-afe8-d92cd89333da.png)

2. Minor is a subset of Major
       A user would take pictures for 2 subjects, and pick which to be Major and which to be Minor. In this case, Major and Minor pick from the same move pool, but Minors get fewer moves from it. One implementation this would work for is if disciplines influence "super moves", like I think somebody mentioned at one point. If you get three super moves, 2 would come from your major and 1 from your minor, 2 each if you're a dual major (with some downside), and all 3 from one if you're pure, something like that. Of course this structure could be implemented other ways, but the basic idea is that Major and Minor for each discipline shares a move pool, and the user selects from it. This also allows us to add moves to the pool for extra customizability, similar to what I mentioned with universal moves.

![Option 3](https://user-images.githubusercontent.com/98851950/152895740-156ec1ac-5bdd-4f7a-96ae-36d007dfe46e.png)

Like one of these ideas more than the others, got another idea, or an amendment to any of mine? Say so below!

This isn't something we need to do immediately, so I figure we can leave this open to discussion till we reach a point where a decision must be made.

**Comment by Apexal** [comment]
Firstly, fantastic writeup. These are all good possible routes, and we should determine which to go with as soon as possible. Let's discuss this in tomorrow's meeting!

**Comment by talios0** [comment]
I like the idea of separating Minors and Majors between light and strong attacks. It would cut down on some customization, but would be much simpler to create characters the user.

**Comment by BianoBonzo** [comment]
The 4 face buttons on a PS4 controller is the basis of the customization of the Major and Minor attacks. Minors are associated with  "light attacks", and they take 2 buttons. Majors are associated with "heavy attacks", and they take the other 2 buttons.

**Comment by Tevetron** [comment]
I think having two moves for major and two moves for minor along with universal moves would make it fairly simply to implement and would be good at getting you immediately into playing.

**Comment by alexisvh** [comment]
I think keeping the major and minor as separate attacks so users can mix and match without too much work is a good idea, using the 4 main buttons on the controller is also a good layout for these attacks.

**Comment by V-aleria** [comment]
I think it would be best to keep the major and minor separated to determine different sets of moves ("major" moves according to the major and "minor" moves according to the minor). It would also make it more user friendly since there would be less customizations and easier for us to implement the game overall. We could always have updates in the future if we would like to make the customization more detailed.

**Comment by Apexal** [comment]
We can close this now as we've settled on 2 moves from the major (special and heavy special) and 2 from the minor (light punch and light kick)! No double majoring for now, but not choosing a minor means you get all 4 moves from your major.
