### ISSUE TITLE
What's the UI/UX supposed to be?

### ISSUE THREAD

**Issue by talios0** [Apexal/wrathspriter#8]
When creating this app, we need to make sure that the user is able to easily transition between the game and creating the character. While we primarily intend for the user to create characters using a separate mobile device, this may not always be the case so we'll need to design around that too.

## Main Page/Options

Starting with what we know, the user is directed to the character creation screen from the game. This is more of a discussion for Wrathskeller, but how do we achieve this? I think we discussed a QR code. Will we only be able to create a character if we have a valid QR code or is it just a link to the website we can visit at anytime.

The webapp is displayed to the user as a regular website. There is no app to install. Upon reaching the website, the user should be greeted and the character customization process should begin. I've included an example of what this could look like below.

I think that each page should have a help button on it to give the user directions on how to use the webapp. It would help keep wrathspriter as accessible as possible.

<img src = "https://user-images.githubusercontent.com/20057606/153341990-3cc68080-bfad-4ff8-b1b8-6de939dfe456.png" width=25%>

## Character Creation Pages

In order to choose the correct poses for the user, we first need to know the Major & Minor first. The name of the character would likely also go here, but there's nothing preventing it from being included later.

<img src = "https://user-images.githubusercontent.com/20057606/153342095-d3f31f69-accf-4d70-8d00-45069c8def56.png" width=25%>

It will be important for the user to be able to go back and re-take pictures. If we don't include this option, then the user would need to recreate the entire character if they mess up an image. Should any pose be selectable at any time or should you only be able to retake pictures as you take them (see below)? Maybe both? In the same vein, the user should be able to delete characters if they decide they don't want them after making them.

<img src = "https://user-images.githubusercontent.com/20057606/153342163-8e564f0e-2170-4ae3-a0c1-301075b323e5.png" width = 25%>

<img src = "https://user-images.githubusercontent.com/20057606/153342199-9e9e7964-8d25-48b2-9505-65d3979eed23.png" width=25%>

After creating the character, an overview of said character should be shown. This would include the character in a pose, the major and minor, and the character's name at minimum. The user should be able to go back through an "Edit" button, or something similar, at this point. If everything looks good, then a "Done" button should be pressed which would initiate the transfer.

<img src = "https://user-images.githubusercontent.com/20057606/153342626-b1df3c7c-25b7-4859-873b-a3a66cdee126.png" width=25%>

<img src = "https://user-images.githubusercontent.com/20057606/153342627-5d23e62a-6416-475e-9c36-fdd102ad44a5.png" width=25%>

## Editing Character Pages

There is also the issue of editing previous characters. Maybe the option to do this could be located on the first screen before decided to create a character? If so, there should also be an option to send the character to the game directly within the page. I think it would be likely that people would want to send characters to each other without editing them each time.

On the page asking whether to edit or send, there should be an option to either delete the character, edit the character, or send the character. This makes sure all functionality is accessible, whether you just created the character or not.

<img src = "https://user-images.githubusercontent.com/20057606/153342720-14f03c57-69b0-4b03-8f16-4f81e6303850.png" width=25%>
<img src = "https://user-images.githubusercontent.com/20057606/153342721-2be1d56e-3128-4fc3-b53e-9005e01c4f8e.png" width=25%>

But, maybe there's another way to display this information? What do you think?

**Comment by Apexal** [comment]
Great exploration and mock ups. Let's discuss this in today's meeting!

**Comment by ThisMatt** [comment]
A couple thoughts

-show all moves in a slider, similar to your third picture
         -highlight/hold/hover to preview full animation (maybe in place of the larger figure on that third picture)
         -finish button lights up when everything is filled in, maybe unfinished moves also have an indicator (red/green border?)
         -able to exchange universal moves or major-minor in this menu? Maybe if you click a move it gives you an exchange or 
           edit option. It'd have to exchange two moves if you're doing major/minor, of course.

**Comment by Apexal** [comment]
Now that we have mockups, we can close this!
